### ISSUE TITLE
请问楼主使用教程能大致讲一下吗

### ISSUE THREAD

**Issue by 1159544839** [roadwide/qqmessageoutput#1]
现在是Python3.5环境已安装  PIP组件都安装了，

KEY迷失获取了，但是不知道在哪里Python代码添加加密文件

**Comment by roadwide** [comment]
README里的那几行代码加到源代码里，设置数据库文件和key，yourdb.db  yourkey替换为你的

**Comment by 1159544839** [comment]
> README里的那几行代码加到源代码里，设置数据库文件和key，yourdb.db yourkey替换为你的

感谢，我正在尝试
